sudo: false
language: python
python: 3.6
install:
  - pip install fontbakery
script:
  - fontbakery check-googlefonts AnomalyMono.otf
  - fontbakery check-adobefonts AnomalyMono.otf
  - fontbakery check-fontval AnomalyMono.otf
