name: fontbakery-universal

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install fontbakery
      run: |
        python -m pip install --upgrade pip
        pip install fontbakery
    - name: Run fontbakery
      run: fontbakery check-universal AnomalyMonoRegular.otf
